GET http://localhost:8080/hello
Accept: application/json

###gtr

POST http://localhost:8080/hello/post
Content-Type: application/x-www-form-urlencoded

name=Test

###ptrp

GET http://localhost:8080/hello/list
Accept: application/json

###